<?php
/**
 * FreshReleasesPayloadReleasesInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ListenBrainz Swagger - OpenAPI 3.0
 *
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FreshReleasesPayloadReleasesInner Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FreshReleasesPayloadReleasesInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'freshReleases_payload_releases_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'artist_credit_name' => 'string',
        'artist_mbids' => 'string[]',
        'listen_count' => 'int',
        'release_date' => 'string',
        'release_group_mbid' => 'string',
        'release_group_primary_type' => 'string',
        'release_mbid' => 'string',
        'release_name' => 'string',
        'release_tags' => 'array<string,string>[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'artist_credit_name' => null,
        'artist_mbids' => 'uuid',
        'listen_count' => null,
        'release_date' => null,
        'release_group_mbid' => 'uuid',
        'release_group_primary_type' => null,
        'release_mbid' => 'uuid',
        'release_name' => null,
        'release_tags' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'artist_credit_name' => false,
        'artist_mbids' => false,
        'listen_count' => false,
        'release_date' => false,
        'release_group_mbid' => false,
        'release_group_primary_type' => false,
        'release_mbid' => false,
        'release_name' => false,
        'release_tags' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'artist_credit_name' => 'artist_credit_name',
        'artist_mbids' => 'artist_mbids',
        'listen_count' => 'listen_count',
        'release_date' => 'release_date',
        'release_group_mbid' => 'release_group_mbid',
        'release_group_primary_type' => 'release_group_primary_type',
        'release_mbid' => 'release_mbid',
        'release_name' => 'release_name',
        'release_tags' => 'release_tags'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'artist_credit_name' => 'setArtistCreditName',
        'artist_mbids' => 'setArtistMbids',
        'listen_count' => 'setListenCount',
        'release_date' => 'setReleaseDate',
        'release_group_mbid' => 'setReleaseGroupMbid',
        'release_group_primary_type' => 'setReleaseGroupPrimaryType',
        'release_mbid' => 'setReleaseMbid',
        'release_name' => 'setReleaseName',
        'release_tags' => 'setReleaseTags'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'artist_credit_name' => 'getArtistCreditName',
        'artist_mbids' => 'getArtistMbids',
        'listen_count' => 'getListenCount',
        'release_date' => 'getReleaseDate',
        'release_group_mbid' => 'getReleaseGroupMbid',
        'release_group_primary_type' => 'getReleaseGroupPrimaryType',
        'release_mbid' => 'getReleaseMbid',
        'release_name' => 'getReleaseName',
        'release_tags' => 'getReleaseTags'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('artist_credit_name', $data ?? [], null);
        $this->setIfExists('artist_mbids', $data ?? [], null);
        $this->setIfExists('listen_count', $data ?? [], null);
        $this->setIfExists('release_date', $data ?? [], null);
        $this->setIfExists('release_group_mbid', $data ?? [], null);
        $this->setIfExists('release_group_primary_type', $data ?? [], null);
        $this->setIfExists('release_mbid', $data ?? [], null);
        $this->setIfExists('release_name', $data ?? [], null);
        $this->setIfExists('release_tags', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets artist_credit_name
     *
     * @return string|null
     */
    public function getArtistCreditName()
    {
        return $this->container['artist_credit_name'];
    }

    /**
     * Sets artist_credit_name
     *
     * @param string|null $artist_credit_name artist_credit_name
     *
     * @return self
     */
    public function setArtistCreditName($artist_credit_name)
    {
        if (is_null($artist_credit_name)) {
            throw new \InvalidArgumentException('non-nullable artist_credit_name cannot be null');
        }
        $this->container['artist_credit_name'] = $artist_credit_name;

        return $this;
    }

    /**
     * Gets artist_mbids
     *
     * @return string[]|null
     */
    public function getArtistMbids()
    {
        return $this->container['artist_mbids'];
    }

    /**
     * Sets artist_mbids
     *
     * @param string[]|null $artist_mbids artist_mbids
     *
     * @return self
     */
    public function setArtistMbids($artist_mbids)
    {
        if (is_null($artist_mbids)) {
            throw new \InvalidArgumentException('non-nullable artist_mbids cannot be null');
        }
        $this->container['artist_mbids'] = $artist_mbids;

        return $this;
    }

    /**
     * Gets listen_count
     *
     * @return int|null
     */
    public function getListenCount()
    {
        return $this->container['listen_count'];
    }

    /**
     * Sets listen_count
     *
     * @param int|null $listen_count listen_count
     *
     * @return self
     */
    public function setListenCount($listen_count)
    {
        if (is_null($listen_count)) {
            throw new \InvalidArgumentException('non-nullable listen_count cannot be null');
        }
        $this->container['listen_count'] = $listen_count;

        return $this;
    }

    /**
     * Gets release_date
     *
     * @return string|null
     */
    public function getReleaseDate()
    {
        return $this->container['release_date'];
    }

    /**
     * Sets release_date
     *
     * @param string|null $release_date release_date
     *
     * @return self
     */
    public function setReleaseDate($release_date)
    {
        if (is_null($release_date)) {
            throw new \InvalidArgumentException('non-nullable release_date cannot be null');
        }
        $this->container['release_date'] = $release_date;

        return $this;
    }

    /**
     * Gets release_group_mbid
     *
     * @return string|null
     */
    public function getReleaseGroupMbid()
    {
        return $this->container['release_group_mbid'];
    }

    /**
     * Sets release_group_mbid
     *
     * @param string|null $release_group_mbid release_group_mbid
     *
     * @return self
     */
    public function setReleaseGroupMbid($release_group_mbid)
    {
        if (is_null($release_group_mbid)) {
            throw new \InvalidArgumentException('non-nullable release_group_mbid cannot be null');
        }
        $this->container['release_group_mbid'] = $release_group_mbid;

        return $this;
    }

    /**
     * Gets release_group_primary_type
     *
     * @return string|null
     */
    public function getReleaseGroupPrimaryType()
    {
        return $this->container['release_group_primary_type'];
    }

    /**
     * Sets release_group_primary_type
     *
     * @param string|null $release_group_primary_type release_group_primary_type
     *
     * @return self
     */
    public function setReleaseGroupPrimaryType($release_group_primary_type)
    {
        if (is_null($release_group_primary_type)) {
            throw new \InvalidArgumentException('non-nullable release_group_primary_type cannot be null');
        }
        $this->container['release_group_primary_type'] = $release_group_primary_type;

        return $this;
    }

    /**
     * Gets release_mbid
     *
     * @return string|null
     */
    public function getReleaseMbid()
    {
        return $this->container['release_mbid'];
    }

    /**
     * Sets release_mbid
     *
     * @param string|null $release_mbid release_mbid
     *
     * @return self
     */
    public function setReleaseMbid($release_mbid)
    {
        if (is_null($release_mbid)) {
            throw new \InvalidArgumentException('non-nullable release_mbid cannot be null');
        }
        $this->container['release_mbid'] = $release_mbid;

        return $this;
    }

    /**
     * Gets release_name
     *
     * @return string|null
     */
    public function getReleaseName()
    {
        return $this->container['release_name'];
    }

    /**
     * Sets release_name
     *
     * @param string|null $release_name release_name
     *
     * @return self
     */
    public function setReleaseName($release_name)
    {
        if (is_null($release_name)) {
            throw new \InvalidArgumentException('non-nullable release_name cannot be null');
        }
        $this->container['release_name'] = $release_name;

        return $this;
    }

    /**
     * Gets release_tags
     *
     * @return array<string,string>[]|null
     */
    public function getReleaseTags()
    {
        return $this->container['release_tags'];
    }

    /**
     * Sets release_tags
     *
     * @param array<string,string>[]|null $release_tags release_tags
     *
     * @return self
     */
    public function setReleaseTags($release_tags)
    {
        if (is_null($release_tags)) {
            throw new \InvalidArgumentException('non-nullable release_tags cannot be null');
        }
        $this->container['release_tags'] = $release_tags;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


