<?php
/**
 * PlaylistTrackInnerExtensionHttpsMusicbrainzOrgDocJspfTrack
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Listenbrainz
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ListenBrainz Swagger - OpenAPI 3.0
 *
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Listenbrainz\Model;

use \ArrayAccess;
use \Listenbrainz\ObjectSerializer;

/**
 * PlaylistTrackInnerExtensionHttpsMusicbrainzOrgDocJspfTrack Class Doc Comment
 *
 * @category Class
 * @package  Listenbrainz
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PlaylistTrackInnerExtensionHttpsMusicbrainzOrgDocJspfTrack implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'playlist_track_inner_extension_https___musicbrainz_org_doc_jspf_track';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'artist_identifiers' => 'string[]',
        'release_identifier' => 'string',
        'added_at' => 'string',
        'added_by' => 'string',
        'additional_metadata' => '\Listenbrainz\Model\PlaylistTrackInnerExtensionHttpsMusicbrainzOrgDocJspfTrackAdditionalMetadata'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'artist_identifiers' => null,
        'release_identifier' => null,
        'added_at' => null,
        'added_by' => null,
        'additional_metadata' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'artist_identifiers' => false,
        'release_identifier' => false,
        'added_at' => false,
        'added_by' => false,
        'additional_metadata' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'artist_identifiers' => 'artist_identifiers',
        'release_identifier' => 'release_identifier',
        'added_at' => 'added_at',
        'added_by' => 'added_by',
        'additional_metadata' => 'additional_metadata'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'artist_identifiers' => 'setArtistIdentifiers',
        'release_identifier' => 'setReleaseIdentifier',
        'added_at' => 'setAddedAt',
        'added_by' => 'setAddedBy',
        'additional_metadata' => 'setAdditionalMetadata'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'artist_identifiers' => 'getArtistIdentifiers',
        'release_identifier' => 'getReleaseIdentifier',
        'added_at' => 'getAddedAt',
        'added_by' => 'getAddedBy',
        'additional_metadata' => 'getAdditionalMetadata'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('artist_identifiers', $data ?? [], null);
        $this->setIfExists('release_identifier', $data ?? [], null);
        $this->setIfExists('added_at', $data ?? [], null);
        $this->setIfExists('added_by', $data ?? [], null);
        $this->setIfExists('additional_metadata', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets artist_identifiers
     *
     * @return string[]|null
     */
    public function getArtistIdentifiers()
    {
        return $this->container['artist_identifiers'];
    }

    /**
     * Sets artist_identifiers
     *
     * @param string[]|null $artist_identifiers artist_identifiers
     *
     * @return self
     */
    public function setArtistIdentifiers($artist_identifiers)
    {
        if (is_null($artist_identifiers)) {
            throw new \InvalidArgumentException('non-nullable artist_identifiers cannot be null');
        }
        $this->container['artist_identifiers'] = $artist_identifiers;

        return $this;
    }

    /**
     * Gets release_identifier
     *
     * @return string|null
     */
    public function getReleaseIdentifier()
    {
        return $this->container['release_identifier'];
    }

    /**
     * Sets release_identifier
     *
     * @param string|null $release_identifier release_identifier
     *
     * @return self
     */
    public function setReleaseIdentifier($release_identifier)
    {
        if (is_null($release_identifier)) {
            throw new \InvalidArgumentException('non-nullable release_identifier cannot be null');
        }
        $this->container['release_identifier'] = $release_identifier;

        return $this;
    }

    /**
     * Gets added_at
     *
     * @return string|null
     */
    public function getAddedAt()
    {
        return $this->container['added_at'];
    }

    /**
     * Sets added_at
     *
     * @param string|null $added_at added_at
     *
     * @return self
     */
    public function setAddedAt($added_at)
    {
        if (is_null($added_at)) {
            throw new \InvalidArgumentException('non-nullable added_at cannot be null');
        }
        $this->container['added_at'] = $added_at;

        return $this;
    }

    /**
     * Gets added_by
     *
     * @return string|null
     */
    public function getAddedBy()
    {
        return $this->container['added_by'];
    }

    /**
     * Sets added_by
     *
     * @param string|null $added_by added_by
     *
     * @return self
     */
    public function setAddedBy($added_by)
    {
        if (is_null($added_by)) {
            throw new \InvalidArgumentException('non-nullable added_by cannot be null');
        }
        $this->container['added_by'] = $added_by;

        return $this;
    }

    /**
     * Gets additional_metadata
     *
     * @return \Listenbrainz\Model\PlaylistTrackInnerExtensionHttpsMusicbrainzOrgDocJspfTrackAdditionalMetadata|null
     */
    public function getAdditionalMetadata()
    {
        return $this->container['additional_metadata'];
    }

    /**
     * Sets additional_metadata
     *
     * @param \Listenbrainz\Model\PlaylistTrackInnerExtensionHttpsMusicbrainzOrgDocJspfTrackAdditionalMetadata|null $additional_metadata additional_metadata
     *
     * @return self
     */
    public function setAdditionalMetadata($additional_metadata)
    {
        if (is_null($additional_metadata)) {
            throw new \InvalidArgumentException('non-nullable additional_metadata cannot be null');
        }
        $this->container['additional_metadata'] = $additional_metadata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
