<?php
/**
 * ListeningActivityForUserPayloadListeningActivityInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Listenbrainz
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ListenBrainz Swagger - OpenAPI 3.0
 *
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Listenbrainz\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ListeningActivityForUserPayloadListeningActivityInnerTest Class Doc Comment
 *
 * @category    Class
 * @description ListeningActivityForUserPayloadListeningActivityInner
 * @package     Listenbrainz
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListeningActivityForUserPayloadListeningActivityInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListeningActivityForUserPayloadListeningActivityInner"
     */
    public function testListeningActivityForUserPayloadListeningActivityInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "from_ts"
     */
    public function testPropertyFromTs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "listen_count"
     */
    public function testPropertyListenCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "time_range"
     */
    public function testPropertyTimeRange()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "to_ts"
     */
    public function testPropertyToTs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
