<?php
/**
 * LbStatsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ListenBrainz Swagger - OpenAPI 3.0
 *
 * OpenAPI client defintion.
 *
 * The version of the OpenAPI document: v-2024-07-17.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LbStatsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LbStatsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for artistMapForUser
     *
     * Get the artist map for user 'user_name'..
     *
     */
    public function testArtistMapForUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dailyActivityForUser
     *
     * Get the daily activity for user 'user_name'..
     *
     */
    public function testDailyActivityForUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listenersForArtist
     *
     * Get top listeners for artist 'artist_mbid'..
     *
     */
    public function testListenersForArtist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listenersForReleaseGroup
     *
     * Get top listeners for release group 'release_group_mbid'..
     *
     */
    public function testListenersForReleaseGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listeningActivityForUser
     *
     * Get the listening activity for user 'user_name'..
     *
     */
    public function testListeningActivityForUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sitewideArtistMap
     *
     * Get sitewide top recordings..
     *
     */
    public function testSitewideArtistMap()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sitewideListeningActivity
     *
     * Get sitewide top recordings..
     *
     */
    public function testSitewideListeningActivity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sitewideTopArtists
     *
     * Get sitewide top artists..
     *
     */
    public function testSitewideTopArtists()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sitewideTopRecordings
     *
     * Get sitewide top recordings..
     *
     */
    public function testSitewideTopRecordings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sitewideTopReleaseGroups
     *
     * Get sitewide top release groups..
     *
     */
    public function testSitewideTopReleaseGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sitewideTopReleases
     *
     * Get sitewide top releases..
     *
     */
    public function testSitewideTopReleases()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for topArtistsForUser
     *
     * Get top artists for user 'user_name'..
     *
     */
    public function testTopArtistsForUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for topRecordingsForUser
     *
     * Get top recordings for user 'user_name'..
     *
     */
    public function testTopRecordingsForUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for topReleaseGroupsForUser
     *
     * Get top release groups for user 'user_name'..
     *
     */
    public function testTopReleaseGroupsForUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for topReleasesForUser
     *
     * Get top releases for user 'user_name'..
     *
     */
    public function testTopReleasesForUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for yearInMusicForUser
     *
     * Get sitewide top recordings..
     *
     */
    public function testYearInMusicForUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
